# export SELECT_VERSION_xrun=21.09.006_xcelium
# export SPYGLASS_HOME=/cad/synopsys/spyglass/S-2021.09-SP2-1/SPYGLASS_HOME
# export SPYGLASS_DC_PATH=/cad/synopsys/spyglass/S-2021.09-SP2-1

dir:
		mkdir ./03_Sim ;\
		mkdir ./03_Sim/1_func ;\
		mkdir ./03_Sim/2_pre ;\
		mkdir ./03_Sim/3_post ;\
		mkdir ./04_Lint ;\
		mkdir ./05_Pre_Synthesis
