all: make_dir

make_dir:
		echo "==== directory list ===="
		ls -al ./
		@read -p "Type PROJECT Name: " prj_name ;\
		mkdir $${prj_name} ;\
		mkdir $${prj_name}/01_Lib ;\
		mkdir $${prj_name}/02_Env ;\
		mkdir $${prj_name}/02_Env/01_Source_Code ;\
		mkdir $${prj_name}/02_Env/02_SDC ;\
		mkdir $${prj_name}/02_Env/03_Lint ;\
		mkdir $${prj_name}/02_Env/04_Pre_Synthesis ;\
		mkdir $${prj_name}/03_Sim ;\
		mkdir $${prj_name}/03_Sim/1_func ;\
		mkdir $${prj_name}/03_Sim/2_pre ;\
		mkdir $${prj_name}/03_Sim/3_post ;\
		mkdir $${prj_name}/04_Lint ;\
		mkdir $${prj_name}/05_Pre_Synthesis
