# export SELECT_VERSION_xrun=21.09.006_xcelium
# export SPYGLASS_HOME=/cad/synopsys/spyglass/S-2021.09-SP2-1/SPYGLASS_HOME
# export SPYGLASS_DC_PATH=/cad/synopsys/spyglass/S-2021.09-SP2-1

dir:
		mkdir ~/PROJECT/01_Project_Setting ;\
		mkdir ~/PROJECT/01_Project_Setting/03_Sim ;\
		mkdir ~/PROJECT/01_Project_Setting/03_Sim/1_func ;\
		mkdir ~/PROJECT/01_Project_Setting/03_Sim/2_pre ;\
		mkdir ~/PROJECT/01_Project_Setting/03_Sim/3_post ;\
		mkdir ~/PROJECT/01_Project_Setting/04_Lint ;\
		mkdir ~/PROJECT/01_Project_Setting/05_Pre_Synthesis
